package com.kepg.glvpen.modules.analysis.domain;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;
import jakarta.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "analysis_column")
@Getter @Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class AnalysisColumn {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 200)
    private String title;

    @Lob
    @Column(columnDefinition = "TEXT")
    private String content;

    @Column(length = 30)
    private String category; // player, team, game, trend

    private Integer relatedTeamId;

    private Integer relatedPlayerId;

    private Integer season;

    @Column(columnDefinition = "JSON")
    private String chartData;

    @Column(nullable = false)
    @Builder.Default
    private LocalDateTime publishDate = LocalDateTime.now();

    @Builder.Default
    private Integer viewCount = 0;

    @Builder.Default
    private Boolean autoGenerated = false;

    @Column(length = 300)
    private String summary;

    @Builder.Default
    private Boolean featured = false;
}
